### PR TITLE
Moved CMC attribution to navbar

### LINKED ISSUE #939: CoinMarketCap Attribution adds a scrollbar in dashboard
### Description

The `Data provided by CoinMarketCap.com](https://coinmarketcap.com/)` Adds a scrollbar at the bottom of the dashboard when the user has no position

### Steps to reproduce

Enter the Stake dashboard with an address that has no position

Image

### Environment

- **OS**: _e.g., Windows, macOS, Linux_
- **Runtime/Browser/Version**: _e.g., Node 22, Chrome 120_
- **Wallet**: _e.g., MetaMask, Trust, Coinbase Wallet_

### PR DESCRIPTION
**Pull request by alvarengathomas**
### Description

Moved CoinMarketCap attribution to the navbar, but the text doesn't fit in just one line as the figma designs require.

- Navbar width have 212px on Figma Design:
Captura de Tela 2025-03-05 às 15 20 07

- Navbar width have 185px on Real Application:
Captura de Tela 2025-03-05 às 15 19 19

### Screenshots
Desktop:
Captura de Tela 2025-03-05 às 15 47 02

Mobile:
Captura de Tela 2025-03-05 às 15 48 01

### Related issue(s)

Closes #939

### Checklist

- [x] Manual testing passed.
- [ ] Automated tests added, or N/A.
- [ ] Documentation updated, or N/A.
- [ ] Environment variables set in CI, or N/A.

### CODE REVIEW

File: webapp/app/[locale]/_components/navbar/index.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ import { HemiLogoFull } from './_components/hemiLogo'
 import { ItemLink, ItemWithSubmenu, NetworkSwitch } from './_components/navItem'
 import { SocialLinks } from './_components/socialLinks'
 import { TermsAndConditions } from './_components/termsAndConditions'
+import { CmcAttribution } from './_components/cmcAttribution'
```
Comment (gabmontes) [inline webapp/app/[locale]/_components/navbar/index.tsx:26]: ESLint warning to fix here.

Comment (alvarengathomas) [reply webapp/app/[locale]/_components/navbar/index.tsx:26]: why prettier doesn't get that?

Comment (gndelia) [reply webapp/app/[locale]/_components/navbar/index.tsx:26]: I think I know why... I'll send a different PR to fix it

Comment (alvarengathomas) [reply webapp/app/[locale]/_components/navbar/index.tsx]: fixed

**Review by gndelia — APPROVED** [review]

**Comment by gndelia** [comment]
I have been reviewing the designs from Nahuel, and our nav bar implementation. It seems Nahuel's designs have 24px space from each side. We can see that here

image

image

Our implementation, however, has 32px on each side

The first fix for that is [in navbar line 47](https://github.com/hemilabs/ui-monorepo/blob/601e0cd4cd599d51d555a74d786662533ee2b6f9/webapp/app/%5Blocale%5D/_components/navbar/index.tsx#L46). I think we need to replace

```tsx
[&>*]:md:ml-4 [&>*]:md:pr-4
```

With

```tsx
[&>*]:md:ml-3 [&>*]:md:pr-3
```

With that, and using `flex` to center the CMC, it seems that it _barely_ fits. Navbar would look like this

image


@dvnahuel  what do you think?

**Review by gabmontes — APPROVED** [review]
