### PR TITLE
Cap bitcoin timestamp from block

### LINKED ISSUE #692: Bitcoin shows an incorrect time in the transaction history
### Description

It shows a date in the future. It is probably a timezone issue, because evm operations work ok

### Steps to reproduce

Just run a deposit in bitcoin, and then go to the tx history

Image

### PR DESCRIPTION
**Pull request by gndelia**
### Description

When depositing Bitcoin, the block timestamp may appear sometimes as a future timestamp. This PR caps the time with the current UTC time, so it never appears as a future date in the tx history.

### Related issue(s)

Closes #692

### Checklist

- [x] Manual testing passed.
- [x] Automated tests added, or N/A.
- [ ] Documentation updated, or N/A.
- [ ] Environment variables set in CI, or N/A.

### CODE REVIEW

**Review by ArturDolzan — DISMISSED** [review]
uACK

File: webapp/utils/bitcoin.ts [hunk 1]
```diff
@@ -23,3 +23,16 @@ export const calculateDepositOutputIndex = (
...
+ * This means that under certain conditions, the timestamp may be visible to the user as "in X minutes",
+ * meaning the date looks like it is in the future. This function caps the timestamp to "now".
+ * If the user ever resyncs, and the timestamp appeared in the past, then we save that.
+ * See https://github.com/hemilabs/ui-monorepo/issues/692
+ */
+export const getBitcoinTimestamp = function (timestamp: bigint | number) {
+  // timestamps from btc are saved in unix format
+  const now = Math.floor(new Date().getTime() / 1000)
+  return Math.min(now, Number(timestamp))
+}
```
Comment (gabmontes) [inline webapp/utils/bitcoin.ts:38]: Does this function receive either bigints or numbers? We may want to stick to just one input type, the one in `*.status.blockTime`.

Comment (gndelia) [reply webapp/utils/bitcoin.ts]: Agree, the type is `number`, so `bigint` was dropped here [76bb03e](https://github.com/hemilabs/ui-monorepo/pull/718/commits/76bb03e49bfa923b401fbad5dbf470cd535948fd)

**Review by ArturDolzan — APPROVED** [review]

**Review by gabmontes — APPROVED** [review]
